### ISSUE TITLE
No icon.

### ISSUE THREAD

**Issue by Ved-un** [EveningStarlight/NoShorts#1]
Hello.     
Thanks for the addon, but for some reason there is no icon, although in the source code they are...    

![flameshot_178](https://github.com/EveningStarlight/NoShorts/assets/48730277/6e08120c-f13c-4cda-9ff9-eaf8934bc675)

**Comment by Ved-un** [comment]
Upgraded and restarted the FF, now everything is OK.    
Thank you.

![flameshot_178_1](https://github.com/EveningStarlight/NoShorts/assets/48730277/df84b215-743f-44e8-af07-98f306e538d7)

**Comment by EveningStarlight** [comment]
Glad you've liked the addon, and that the new version cleared up the issue!
